### ISSUE TITLE
[BUG] Discipline powers can't roll since updated to 5.0.0/5.0.1

### ISSUE THREAD

**Issue by SalithTaydan** [WoD5E-Developers/wod5e#112]
I updated to 5.0.0/5.0.1 and can no longer roll the discipline powers I have on a character by clicking on them, nor can I edit a power.

This happens every time I try, in both Firefox and Chrome.

I used to be able to bring up the roll dialogue for the power when clicking on the dice symbol next to it. I can click the dice symbol next to the Discipline itself, but then I have to select what is rolled each and every time.

Firefox and Chrome/Opera.
Foundry 12.331
WoD 5.0.1

**Comment by Veilza** [comment]
Could you press F12 on your browser after trying to click on a discipline power and see if there's any errors in the "Console" tab?

**Comment by SalithTaydan** [comment]
Error: You are accessing globalThis.randomID which must now be accessed via foundry.utils.randomID
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at get (foundry-esm.js:66671:25)
    at new PopoutModule (popout.js:9:5)
    at Object.fn (popout.js:1400:28)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at Game.setupGame (foundry.js:9098:11)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)

**Comment by Veilza** [comment]
Try disabling the "Popout" module and then trying again.

**Comment by SalithTaydan** [comment]
Disabling modules gets me an error in dicepool-list.js:10
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isEmbedded')
[Detected 1 package: system:vtm5e(5.0.1)]
    at getDicepoolList (dicepool-list.js:10:60)
    at DisciplineItemSheet._prepareContext (wod-item-base.js:109:26)
    at async DisciplineItemSheet._prepareContext (discipline-item-sheet.js:75:18)
    at async #render (foundry-esm.js:44319:23)
    at async Semaphore._try (foundry-esm.js:6645:19)

**Comment by Veilza** [comment]
Ah okay! That error should be getting fixed in the upcoming hotfix, not too long away. So just hang tight!

**Comment by Veilza** [comment]
Just pushed the update - let me know if you're still encountering this issue and I can re-open the issue to investigate further.
