### ISSUE TITLE
[BUG] Deleting disciplines causes render failure

### ISSUE THREAD

**Issue by SalithTaydan** [WoD5E-Developers/wod5e#115]
Deleting a Discipline power closed the character sheet and now it cannot be opened;

foundry-esm.js:44349 Uncaught (in promise) Error: Failed to render Application "VampireActorSheet-Actor.YdmeRcaTVER7YGr8":
Cannot read properties of undefined (reading 'system')
    at #render (foundry-esm.js:44349:15)
    at async Semaphore._try (foundry-esm.js:6645:19)
Caused by: TypeError: Cannot read properties of undefined (reading 'system')
    at prepareDisciplinesContext (prepare-partials.js:25:110)
    at async VampireActorSheet._renderHTML (foundry-esm.js:46063:31)
    at async #render (foundry-esm.js:44340:24)
    at async Semaphore._try (foundry-esm.js:6645:19)

Using Chrome/Opera and Firefox.
12.331
V5 5.0.2

**Comment by Veilza** [comment]
5.0.3 is now released: https://github.com/WoD5E-Developers/wod5e/releases/tag/5.0.3
